---
- hosts: DevOps
  become: true

  tasks:
  - name: Create new file
    file:
      path: /home/bulldozer/ansible_file.txt
      state: touch
      #owner:
      #group:
      #mode: 0* 

  - name: Add new line
    lineinfile:
      path: /home/bulldozer/ansible_file.txt
      line: 'Hi, it's my first Ansible entry!'

  - name: Add a paragraph
    blockinfile:
      path: /home/bulldozer/ansible_file.txt
      block: |
        AuthName "Restricted Access"
        AuthType Basic
        require valid-user 