---
- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Run Composer installer.
  shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer