---
- name: Install Apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Enable reverse-proxy modules
  apache2_module:
    name: "{{item}}"
  with_items:
    - "rewrite"
    - "proxy"
    - "proxy_http"
    - "proxy_balancer"
    - "lbmethod_byrequests"
  notify: 
  - Restart Apache 